Replace cbor with serde_cbor
dspicher/ur-rs pull request #37
Opened 2021-08-02 07:38 UTC by icota

Removed `invalid cbor length for Part` error as it seems not possible to produce from `serde_cbor`.

2021-08-02 08:09 UTC, icota commented
@dspicher I'm addressing the CI failure. I didn't realise clippy is pedantic :man_teacher:

2021-08-06 21:10 UTC, dspicher requested changes

2021-08-06 21:10 UTC, dspicher commented on src/fountain.rs
> +            Part::from_cbor(vec![0x84, 0x1, 0x2, 0x3, 0x4].as_slice())
`vec![a].as_slice()` could be simplified to `&[a]`. This applies in lots of places.

2021-08-06 21:10 UTC, dspicher commented on src/fountain.rs
> +            Ok(v) => anyhow::Result::Ok(v),
The `anyhow::Result::` prefixes should not be necessary in this and the following line.

2021-08-06 21:10 UTC, dspicher commented on src/fountain.rs
>      }
Plz remove the commented code.

2021-08-06 21:11 UTC, dspicher commented
Thanks a lot for the PR, I think that's a great improvement! Can you please squash the two commits?

2021-08-09 08:19 UTC, icota commented
I've addressed your comments and squashed. CI seems to be complaining about unrelated code?

2021-08-09 08:38 UTC, icota commented
I've recreated the CI panic by doing a `rustup update`. Addressed in https://github.com/dspicher/ur-rs/pull/39

2021-08-09 13:53 UTC, merged

2021-08-09 13:59 UTC, dspicher commented
Thanks for your contribution! I'll create a 0.1.0 release when I'm back from vacation.

2021-08-23 10:57 UTC, dspicher commented
@icota fyi I've just published 0.1.0:
https://crates.io/crates/ur/0.1.0