Encoder: add support for UR types other than 'bytes'
dspicher/ur-rs pull request #63
Opened 2021-11-19 09:05 UTC by icota

An attempt to fix https://github.com/dspicher/ur-rs/issues/8. Test is implementing `crypto-request` UR type from [here](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2021-001-request.md).

2021-11-19 11:02 UTC, dspicher commented
Hey @icota thanks a lot for the PR, looks interesting! I just fixed the codecov integration, can you rebase please?

2021-11-19 12:59 UTC, dspicher commented
The test doesn't check for the same UR as in the [spec](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2021-001-request.md#example-request-and-response). Also the hexlified transaction id is a different one, maybe that is the reason?

2021-11-19 13:37 UTC, icota commented
Looks like I pasted the wrong link, sorry! It's actually [this doc](https://github.com/BlockchainCommons/crypto-commons/blob/master/Docs/ur-99-request-response.md). 
I've amended the test comment and the first comment in the PR.

2021-11-19 16:02 UTC, dspicher requested changes

2021-11-19 16:02 UTC, dspicher commented on src/ur.rs
> +    use hex;
this can be removed

2021-11-19 16:02 UTC, dspicher commented on src/ur.rs
> +        let encoded = Encoder::encode(&ur, "bytes".to_string()).unwrap();
`.to_string()` can be removed if you change `encode` as per the other comment

2021-11-19 16:02 UTC, dspicher commented on src/ur.rs
> +        let mut encoder = Encoder::new(&ur, 30, "bytes".to_string()).unwrap();
`.to_string()` can be removed if you change `new` as per the other comment

2021-11-19 16:02 UTC, dspicher commented on src/ur.rs
> +        let e = Encoder::encode(&data, "crypto-request".to_string()).unwrap();
`.to_string()` can be removed if you change `encode` as per the other comment

2021-11-19 16:02 UTC, dspicher commented on src/ur.rs
> +        let mut encoder = Encoder::new(&ur, 1000, "bytes".to_string()).unwrap();
`.to_string()` can be removed if you change `new` as per the other comment

2021-11-19 16:02 UTC, dspicher commented
> Looks like I pasted the wrong link, sorry! It's actually [this doc](https://github.com/BlockchainCommons/crypto-commons/blob/master/Docs/ur-99-request-response.md). I've amended the test comment and the first comment in the PR.

Excellent, thanks. Only some minor stuff left.

2021-11-19 16:03 UTC, dspicher commented on src/ur.rs
> +        // https://github.com/BlockchainCommons/crypto-commons/blob/master/Docs/ur-99-request-response.md
Can we make this more stable by using 
https://github.com/BlockchainCommons/crypto-commons/blob/67ea252f4a7f295bb347cb046796d5b445b3ad3c/Docs/ur-99-request-response.md
?

2021-11-21 15:38 UTC, icota commented
Thanks for the review @dspicher! I believe I have implemented all of your suggestions.

2021-11-21 18:57 UTC, dspicher approved these changes

2021-11-21 18:58 UTC, merged

2021-11-21 18:58 UTC, dspicher commented
LGTM 👍 thanks again for the PR!